name: deploy
on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: SSH into server and run command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            cd /root/KirisameNoSato/
            git pull origin deploy
            npm install
            npm run build
            cd /var/www/kirisamenosato && rm -rf .[^.]* * 2>/dev/null || true
            cp -r /root/KirisameNoSato/build/* .
